### ISSUE TITLE
EXE download link 404's

### ISSUE THREAD

**Issue by kernel-sanders** [open-circle-ltd/chocolatey.microsoft-office-deployment#24]
The [link](https://download.microsoft.com/download/2/7/A/27AF1BE6-DD20-4CB4-B154-EBAB8A7D4A7E/officedeploymenttool_15225-20204.exe), found in the code [here](https://github.com/open-circle-ltd/chocolatey.microsoft-office-deployment/blob/7d20c5508d757460f6229dbd8d48227169a816b1/package/tools/chocolateyinstall.ps1#L7) now results in a 404 which causes this package to fail.

It appears the new link is https://download.microsoft.com/download/2/7/A/27AF1BE6-DD20-4CB4-B154-EBAB8A7D4A7E/officedeploymenttool_15726-20202.exe

**Comment by olifre** [comment]
In theory, this package seems like it uses Chocomilk to automatically find and update to new releases. 
However, the corresponding GitHub Actions workflow does not seem to have run in the past three months (probably due to repo inactivity). 

Likely, one of the repo admins like @sbaerlocher needs to reactivate the GitHub Actions workflow, and Chocomilk should fix this automatically? 
To keep the workflow active in the future, https://github.com/marketplace/actions/keepalive-workflow might be of interest.

**Comment by sbaerlocher** [comment]
@olifre Thanks for pointing this out, I have re-enabled the Github action, chocomilk should update the links in the next 24 hours. 

I'll look at how to avoid the action being decanted in the future.

**Comment by kernel-sanders** [comment]
Fixed by the bot in https://github.com/open-circle-ltd/chocolatey.microsoft-office-deployment/commit/83679ed3b93bad176a795ea7df0464bf9f458e6b

**Comment by pratisharora** [comment]
looks like the issue is back.

**Comment by sbaerlocher** [comment]
@pratisharora Thank you for the reminder. The package with the latest version and valid link was automatically updated at 13:24:43 UTC+0 today and is still in the review process.
https://community.chocolatey.org/packages/microsoft-office-deployment/16.0.15928.20216

**Comment by pratisharora** [comment]
Can you please help with when this will be fixed ?

**Comment by olifre** [comment]
@sbaerlocher It sadly seems like automated review checks keep failing (due to disk space, maybe)? So new versions do not seem to appear in the Chocolatey repo.
